name: Test reusable workflow
on:
  pull_request:
  push:
    branches: [ '**' ]
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  test-workflow:
    name: Test SonarSource/gh-action_sbom on alpine:latest
    uses: ./.github/workflows/workflow.yml
    with:
      image: alpine:latest
      filename: test-workflow-bom.json
      upload-artifact: true
      upload-release-assets: true
  test2-workflow:
    name: Test SonarSource/gh-action_sbom on alpine:latest
    uses: ./.github/workflows/workflow.yml
    with:
      image: alpine:latest
      filename: test-workflow-bom.json
      upload-artifact: false
      upload-release-assets: false
